config/routes.rb
Rails.application.routes.draw do

  get 'votes/create'

  get 'votes/destroy'

  devise_for :users
    resources :books do

      resources :likes, only: [:create, :destroy]
      resources :favourites, only: [:create, :destroy]
    end
    resources :books do
    resources :reviews do
      resources :votes, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
    end
    root "books#index"



end

app/models/book.rb
class Book < ActiveRecord::Base

    belongs_to :user
    belongs_to :category
    has_many :reviews
    has_many :liked_reviews, through: :reviews, source: :user
    has_many :likes, dependent: :destroy
    has_many :liking_users, through: :likes, source: :user
    has_many :favourites, dependent: :destroy
    has_many :favouriting_users, through: :favourites, source: :user


    has_attached_file :book_img, styles: { book_index: "250x350>", :book_show => "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\Z/


      validates :title,      {presence: true,
                              uniqueness: {message: "Title currently exists"},
                              length:     {minimum: 1}}

      validates :description, {presence: true,
                              uniqueness: {scope: :title},
                              length:     {minimum: 1}}



    def liked_by?(user)
      # likes.find_by_user_id(user.id).present?
      like_for(user).present?
    end

    def like_for(user)
      likes.find_by_user_id(user.id)
    end

    def favourited_by?(user)
      favourite_for(user).present?
    end

    def favourite_for(user)
      favourites.find_by_user_id(user.id)
    end



end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :books


end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  belongs_to :review

  validates :book_id, uniqueness: {scope: :user_id}

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  belongs_to :review

  validates :book_id, uniqueness: {scope: :user_id}

end

app/models/review.rb
class Review < ActiveRecord::Base

    belongs_to :book
    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liking_users, through: :likes, source: :user

    has_many :votes, dependent: :destroy
    has_many :voting_users, through: :votes, source: :user



end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :votes, dependent: :nullify
  has_many :voted_questions, dependent: :nullify
  has_many :books, dependent: :nullify
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :nullify
  has_many :liked_books, through: :likes, source: :book
  has_many :liked_reviews, through: :likes, source: :review
  has_many :favourites, dependent: :nullify
  has_many :favourite_books, through: :favourites, source: :book
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :review
  belongs_to :user
  validates :review_id, uniqueness: {scope: :user_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :find_book, only: [:show, :edit, :update, :destroy]

    before_action :authenticate_user!, only: [:new, :edit, :show]

    def index

      if params[:category].blank?
        @books = Book.all.order("created_at DESC")
      else
        @category_id = Category.find_by(name: params[:category])
        @books = Book.where(:category_id => @category_id).order("created_at DESC")
      end
    end


    def show

      if @book.reviews.blank?
        @average_review = 0
      else
        @average_review = @book.reviews.average(:rating).round(2)
      end
    end

    def new
      @book = current_user.books.build
      @categories = Category.all.map { |c| [c.name, c.id]}
    end

    def create
      @book = current_user.books.build book_params
      @book.category_id = params[:category_id]

      if @book.save
        redirect_to root_path
      else
        render 'new'
      end
    end

    def edit
      @categories = Category.all.map { |c| [c.name, c.id]}

    end

    def update
      @book.category_id = params[:category_id]
      if @book.update(book_params)
        redirect_to book_path(@book)
      else
        render 'edit'
      end
    end

    def destroy
      @book.destroy
      redirect_to root_path
    end


    private


    def book_params
      params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
    end

    def find_book
      @book = Book.find params[:id]
    end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :destroy]


  def create
    fav      = current_user.favourites.new
    book     = Book.find params[:book_id]
    # fav.user     = current_user
    fav.book = book
    if fav.save
      redirect_to book_path(book), notice: "Favourited!"
    else
      redirect_to book_path(book), alert: "Error!"
    end
  end

  def destroy
    book = Book.find params[:book_id]
    fav      = current_user.favourites.find params[:id]
    fav.destroy
    redirect_to book_path(book), notice: "UnFavourited!"
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :destroy]


  def create

    like          = Like.new
    book      = Book.find params[:book_id]
    like.book = book
    like.user = current_user
    if like.save
      redirect_to book_path(book), notice: "Thanks for liking!"
    else
      redirect_to book_path(book), alert: "Can't like! Liked already?"
    end
  end

  def destroy

    book = Book.find params[:book_id]
    like     = current_user.likes.find params[:id]
    like.destroy
    redirect_to book_path(book), notice: "Like removed!"

  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]

  before_action :authenticate_user!, only: [:new, :edit]


  def new
    @review = Review.new
  end

  def create
    @review = Review.new review_params

    @review.book_id = @book.id
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to book_path(@book)}
        format.js { render :ajax_create }
      else
        format.html { render 'books/show' }
        format.js   { render :ajax_fail }
      end
    end
  end

  def edit
  end

  def update
    if @review.update review_params
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
      @review = Review.find params[:id]

      @review.destroy
      respond_to do |format|
        format.html { redirect_to book_path(@review.book) }
        format.js   { render }
      end

  end


  private

  def find_review
    @review = Review.find params[:id]
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_book
    @book = Book.find params[:book_id]
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :destroy]


  def create

    vote = current_user.votes.new vote_params
    review = Review.find params[:review_id]
    vote.review = review
    vote.user = current_user
      respond_to do |format|
        if @vote.save
          format.html { render }
          format.js   { render :ajax_vote }
        else
          format.html { render }
          format.js   { render :ajax_votefail }
        end
  end

  private

  def vote_params
    params.require(:vote).permit(:is_up)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/books/_form.html.erb
    <%= simple_form_for @book, :html => { :multipart => true } do |f| %>
      <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Choose your path, young Skywalker...") %>
      <%= f.file_field :book_img %>
      <%= f.input :title, label: "Book Title" %>
      <%= f.input :description, label: "Synopsis" %>
      <%= f.input :author, label: "Author" %>
      <%= f.button :submit, "Engage.", :class => "btn-custom2" %>
    <% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="new-book-form">

<h1>Edit Book</h1>


  <%= simple_form_for @book, :html => { :multipart => true } do |f| %>
    <%= f.select :category_id, @categories %>
    <%= f.file_field :book_img %>

    <%= f.input :title, label: "Book Title" %>
    <%= f.input :description, label: "Book Title: " %>
    <%= f.input :author, label: "Author" %>
    <%= f.button :submit, "Engage.", :class => "btn-custom2" %>
    <% end %>


  </div>

</div>

app/views/books/index.html.erb
  <h1 class="current-category"><%= params[:category] %></h1>

  <% if @books.count == 0 %>

    <h1>There are no book matches in this category.</h1>

  <% else %>

  <div class="row">


  <% @books.each do |book| %>

    <div class="col-md-1">

      <%= image_tag book.book_img.url(:book_index), class: "book" %>
      <a href="/books/<%= book.id %>">



        <body>




      </a>

      </div>

    <% end %>


  </div>

<% end %>

<hr><hr>

<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>

  <h1>There are no book matches in this category.</h1>

<% else %>

<div class="row">


<% @books.each do |book| %>

  <div class="col-md-2">

    <a href="/books/<%= book.id %>">
      <%= image_tag book.book_img.url(:book_index), class: "book" %>
    </a>

    </div>

  <% end %>

<%= link_to "Add Book", new_book_path %>

</div>

<% end %>

<hr><hr>

<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>

  <h1>There are no book matches in this category.</h1>

<% else %>

<div class="row">


<% @books.each do |book| %>

  <div class="col-md-3">

    <a href="/books/<%= book.id %>">
      <%= image_tag book.book_img.url(:book_index), class: "book" %>
    </a>

    </div>

  <% end %>

<%= link_to "Add Book", new_book_path %>

</div>

<% end %>

<hr><hr>

<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>

  <h1>There are no book matches in this category.</h1>

<% else %>

<div class="row">


<% @books.each do |book| %>

  <div class="col-md-4">

    <a href="/books/<%= book.id %>">
      <%= image_tag book.book_img.url(:book_index), class: "book" %>
    </a>

    </div>

  <% end %>

<%= link_to "Add Book", new_book_path %>

</div>

<% end %>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="new-book-form">


      <h1>New Book</h1>

      <%= render 'form' %>


  </div>

</div>

app/views/books/show.html.erb
  <div class="row">

    <div class="col-md-4" style="text-align: right;">

      <%= image_tag @book.book_img.url(:book_show), class: "book-show" %>

  <div class="bed-book">

    <% if user_signed_in? %>

    <% if @book.user_id == current_user.id %>

    <%= link_to "Back", root_path, class: "btn btn-custom" %>
    <%= link_to "Edit", edit_book_path(@book), class: "btn btn-custom" %>
    <%= link_to "Delete", book_path(@book), method: :delete, data: {confirm: "Confirm Deletion?"}, class: "btn btn-custom" %>

    <% end %>

    <% end %>
  </div>
    </div>


    <div class="col-md-8">

      <div class="book-info">




      <h2 class="book-title"><%= @book.title %></h2>
      <h3 class="book-author"> <span>From</span> <%= @book.author %></h3>
      <h2 class="avg-rating">Average Rating</h2>
      <div class="average-review-rating" data-score=<%= @average_review %>></div>
      <span class="number-of-reviews">Based on <%= pluralize(@book.reviews.count, "review") %></span>
        <br>
      <% if user_signed_in? && @book.liked_by?(current_user) %>
      <%= link_to fa_icon("thumbs-up"), book_like_path(@book, @book.like_for(current_user)),
                    method: :delete, class: "icon-big" %>
      <% else %>
      <%= link_to fa_icon("thumbs-o-up"), book_likes_path(@book), class: "icon-big",
                      method: :post %>
      <% end %>
      <%= pluralize(@book.likes.count, "like") %>

      <% if user_signed_in? && @book.favourited_by?(current_user) %>
      <%= link_to fa_icon("star"), [@book, @book.favourite_for(current_user)],
                method: :delete, class: "icon-big" %>
      <% else %>
      <%= link_to fa_icon("star-o"), book_favourites_path(@book), method: :post,
                class: "icon-big" %>
      <% end %>
      <%= pluralize(@book.favourites.count, "favourite") %>


      <p class="book-desc"><%= @book.description %></p>


      </div>
    </div>

  </div>







<div class="row">

    <div class="col-md-4">

      <div class="reviews">

      <h1>Reviews</h1>


      <%= render 'reviews/form' %>

      <div id="reviews">
        <% @book.reviews.each do |r| %>
        <%= render "reviews/review", review: r %>
        <% end %>
      </div>

      <div>
        <%= link_to "Add Review", new_book_review_path(@book), class: "btn-custom" %>
      </div>

    </div>

  </div>

</div>



  <script>
    $('.review-rating').raty({
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      },
      path: '/assets/'
    });
  </script>

  <script>
    $('.average-review-rating').raty({
      readOnly: true,
      path: '/assets/',
      score: function() {
        return $(this).attr('data-score')
      }
    });
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <nav class="navbar navbar-default">

        <div class="container">

          <div class="navbar-header">
            <%= link_to "Book Blog", root_path, class: "navbar-brand" %>
          </div>

          <ul class="nav navbar-nav">
            <li><%= link_to "Sign Up", new_user_registration_path %></li>

            <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
            <% end %>
          </ul>

            <ul class="nav navbar-nav navbar-right">

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories </a>
                <ul class="dropdown-menu" role="menu">
                  <% Category.all.each do |category| %>
                    <li class="<%= 'active' if params[:category] == category.name %>">
                      <%= link_to category.name, books_path(category: category.name), class: "link" %>
                    </li>
                  <% end %>

                </ul>

              </li>


              <% if user_signed_in? %>
                <li><%= link_to "Add Book", new_book_path %></li>
              <% end %>

            </ul>


        </div>

    </nav>



      <div class="container">
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
      </div>

</body>
</html>

app/views/reviews/_form.html.erb
  <%= simple_form_for [@book, @book.reviews.build], remote: true do |f| %>
    <div id="rating-form">
      <label>Rating: </label>
    </div>

    <%= f.input :comment %>
    <%= f.button :submit, :class => "btn-custom2" %>

  <% end %>


    <script>
      $('#rating-form').raty({
        path: '/assets/',
        scoreName: 'review[rating]'
      });
    </script>

app/views/reviews/_review.html.erb
<div class="review" id="<%= dom_id(review) %>">

  <div class="review-rating" data-score="<%= review.rating %>"></div>

    <p class="review-comment"><%= review.comment %></p>


      <% if user_signed_in? %>

        <% if review.user_id == current_user.id %>

          <div class="links btn-group">

      <%= link_to "Edit", edit_book_review_path(review.book, review), class: "btn btn-custom" %>
      <%= link_to "Delete", book_review_path(review.book, review), method: :delete,
                                                                   class: "btn btn-custom",
                                                                   remote: true %>

          </div>

        <% end %>

      <% end %>

  </div>

app/views/reviews/ajax_create.js.erb
$("#reviews").prepend("<%= j render 'review', review: @review %>");

app/views/reviews/ajax_fail.js.erb
$("#new_review").replaceWith("<%= j render 'reviews/form' %>");

app/views/reviews/destroy.js.erb
$("#<%= dom_id(@review) %>").fadeOut(700, function(){ (this).remove(); })

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="new-book-form">

  <h1>Edit Review</h1>

  <%= simple_form_for [@book, @review] do |f| %>
  <div id="rating-form">
    <label>Rating: </label>
  </div>

    <%= f.input :comment %>
    <%= f.button :submit, :class => "btn-custom2" %>
    <% end %>

  </div>

</div>

    <script>
      $('#rating-form').raty({
        path: '/assets/',
        scoreName: 'review[rating]'
      });
    </script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="new-book-form">

<h1>New Review</h1>

<%= render 'form' %>

  </div>

</div>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>